### PR TITLE
Release

### PR DESCRIPTION
**Pull request by tejdnk**
I am Nirmal Tej Kumar interested in adding my profile to your current users list.
I request the concerned staff to kindly add my profile to the current users list.

My Details : NirmalTejKumar current member - 1. Ante Inst,UTD,Dallas,TX,USA. 2. Researcher - IST,UNESP,Sorocaba,SP,Brazil.
Websites : 1. www.anteinstiute.org 2.www.sorocaba.unesp.br

Thanks/best rgds,
Nirmal - Brazil/USA.

### CODE REVIEW

**Comment by tejdnk** [comment]
Thanks for your time.Looking forward. Nirmal

**Comment by erik-brangs** [comment]
If you want to be added to the users list at http://www.jikesrvm.org/Resources/CurrentUsers/ , the easiest way would be to modify the website sources yourself and then submit a pull request against the website repository.

You already seem to have a fork of the right repository. In the file tree, the sources for the users list are under Resources/CurrentUsers.md . They're written in GitHub-flavored markdown. GitHub provides some information about Markdown at https://help.github.com/articles/basic-writing-and-formatting-syntax/ .

**Comment by tejdnk** [comment]
### [ante Institute,UTD,Dallas,TX,USA](http://www.anteinstitute.org)
### [IST,UNESP,Sorocaba,SP,Brazil](www.sorocaba.unesp.br)
#- [NirmalTejKumar](http://www.anteinstitute.org/index.php?page=currentmembers)

**Comment by erik-brangs** [comment]
I've added you to the current users list with [this commit](https://github.com/JikesRVM/jikesrvm.github.io/commit/b408bbb6ce49437679a5a2b789f2996cedbe51aa). The changes are already live at http://www.jikesrvm.org/Resources/CurrentUsers/ .

If you'd rather have your name appear differently on the website, feel free to submit a pull request against the [website repository](https://github.com/JikesRVM/jikesrvm.github.io).

**Pull request closed without merging**
