### PR TITLE
TPH CL1 - Add support for aligned SysCalls

### PR DESCRIPTION
**Pull request by javadamiri**
This is the first of a series of PRs to add the support for [Rust-MMTk](https://github.com/mmtk/mmtk-core) as a third-party-heap (TPH) for JikesRVM.

This PR adds support for aligned system calls.
In the future PRs, these system calls will be used by JikesRVM to call into Rust-MMTk to perform various functions, such as allocation and checking reference liveness.

This PR also adds the following two tests for aligned system calls to pre-commit tests:

```
public void sysTestStackAlignment0();
public int sysTestStackAlignment5(int a, int b, int c, int d, int e);
```

### CODE REVIEW

**Comment by erik-brangs** [comment]
Thanks.

Here's my first round of feedback:

General comments
- the term TPH needs to be defined somewhere. At the very least, you should rename `sysTph.c` and the `tph` test run, e.g. to `sysThirdPartyHeap.c` and `third-party-heap`. If you're willing to write more documentation, the sources for the website and the user guide can be found in the repository at https://github.com/JikesRVM/jikesrvm.github.io .
- the pull request breaks the build on the machines I tested on because the `build-tph-test-lib` target fails:

> build-tph-test-lib:
>     [echo] Creating TPH test SysCalls library for target: 64-Bits
>     [exec] error: no such subcommand: `+nightly`

- Problems in the third party heap implementation should not break the build until it is the default implementation. For now, you could add a config flag, similar to `config.include.gcspy` or `classlib.provider`. The main build file `build.xml` should avoid pulling in stuff from testing. You could try putting `build_tph_test_lib.xml` into `build/components`.
- Which architectures are you targeting? x86? x64? Are you interested in supporting other architectures for Jikes RVM or are you doing that with other VM implementations? There is code for a 32-bit ARM baseline port that I could try merging if there was interest and someone can test (I don't have suitable hardware).
- The setup of your test runs is unclear to me. If you want to test basic functionality in `pre-commit`, you want to add your tests to `protoype` (in order to get it baseline compiled) and `development_Opt_1` (in order to get it opt-compiled). `development` is interesting for larger benchmarks that show on-stack-replacement or garbage collection. I don't understand the purpose of the `tphtests` run. Could you elaborate?

Code review
I'll give more feedback when I can actually build with the changes. For now, I only have these comments:

- in the PPC `StackManager`, use `OptimizingCompilerException.UNREACHABLE()` to bail out. In general, you should use `OptimizingCompilerException` in the optimizing compiler when you encounter a problem that can be solved by using the baseline compiler instead. If recovery isn't possible, use `if (VM.VerifyAssertions) VM._assert` or `VM.sysFail`.
- It's possible that the current version breaks PPC builds because `ALIGNED_SYSCALL` won't be implemented there. This would cause development builds to fail when they encounter a `ALIGNED_SYSCALL` instruction. However, I can't build with the changes right now, so I can't say for sure.

**Comment by javadamiri** [comment]
Hi Erik,

Thanks for the review,
I'm working on your feedback and will push/propose changes asap.
In the meantime, the error you're getting (`error: no such subcommand: +nightly`) is most probably because you don't have a suitable nightly version of Rust installed. For example, people have reported this error for rust toolchain installed from Ubuntu repos. Removing the current version and reinstalling the latest nightly version using [Rustup](https://rustup.rs/) seems to solve the issue for them.

**Comment by javadamiri** [comment]
About `Which architectures are you targeting?`:

Currently, we only support x86 (32-bits) for JikesRVM.
I don't think there is any short-term plan for supporting other architectures.
@steveblackburn knows more about these policies for Rust MMTk, but I assume we should now continue with only 32-bits x86.

**Comment by erik-brangs** [comment]
General comments

Unfortunately, the build is broken on PPC. The problem is with the `ALIGNED_SYSCALL` instruction. The code for the opt-compiled PPC bootimage (e.g. `development`) still has at least one aligned syscall instruction in it which causes the build to fail:

> Compiler failure during compilation of < BootstrapCL, Lorg/jikesrvm/runtime/SysCallImpl; >.test_stack_alignment_0 ()V
> java.lang.RuntimeException: vm internal error at:
> 	at org.jikesrvm.VM._assertionFailure(VM.java:804)
> 	at org.jikesrvm.VM._assert(VM.java:785)
> 	at org.jikesrvm.VM._assert(VM.java:760)
> 	at org.jikesrvm.runtime.Magic.getThreadRegister(Magic.java:69)
> 	at org.jikesrvm.ppc.ThreadLocalState.getCurrentThread(ThreadLocalState.java:42)
> 	at org.jikesrvm.scheduler.RVMThread.getCurrentThread(RVMThread.java:2626)
> 	at org.jikesrvm.VM.sysFail(VM.java:2458)
> 	at org.jikesrvm.compilers.opt.lir2mir.ConvertLIRtoMIR$ReduceOperators.expandAlignedSysCall(ConvertLIRtoMIR.java:169)

You could work around this by changing the instruction after it was generated by `BC2IR`. This could be done with an architecture-specific phase (similar to `InsertIMMQ_MOVForX64`). The `ALIGNED_SYSCALL` instructions could be rewritten (e.g. to a new trap or to a new runtime service method) so that it fails at runtime. Failures at run time are fine for this case because the build will fail on unsupported architectures anyway.

Additionally, `TestSysCalls` fails on x64 baseline compiler with the changes applied.

Code review

`BaselineCompilerImpl`
-- replace numbers with associated constants where possible. Introduce new ones if needed (e.g. for `alignStack`).
-- `if (m.isStackAligned() && VM.BuildFor32Addr)`: `VM.BuildFor32Addr` should be first
-- the stack alignment code is getting quite long and hard to read but I suppose we could refactor it later

`BURS_Helpers`
- `ALIGNED_SYSCALL` seems very similar to `SYSCALL`. Can you extract shared code?

`CallingConvention`
- you're re-using `MARKER` from x64 in `alignStackForX32SysCall` so its comment needs to be updated
- the expression in `IC(..)` in `alignStackForX32SysCall` is too hard too read. At the very least, you should put it into a variable.
- in `expandAlignedSysCall`, the comment in the penultimate line is wrong
- in `expandAlignedSysCall`, you could extract part of the method into a methods shared with `expandSysCall`

**Comment by erik-brangs** [comment]
Is anyone still working on this from the MMTk side?

**Pull request closed without merging**
