### PR TITLE
Fix size checks to fail properly on negative values

### PR DESCRIPTION
**Pull request by dmitry-brizhinev**

### CODE REVIEW

**Comment by dmitry-brizhinev** [comment]
Ok I'll get onto that tomorrow

**Comment by dmitry-brizhinev** [comment]
Updated. I noticed that my changes fixed the 1 << 29 case but broke the -5 case, so I altered it to this version.

**Comment by erik-brangs** [comment]
Looks pretty good so far.

I have got a few suggestions for the test, though:
- The test looks more like a test from the normal test runs than a (J)unit test. You could rename it to MemoryManagerTest.
- You test the size check in `allocateArray`. You could just call `allocateArray` directly and fake most of the parameters. After all, you're only interested in seeing the `OutOfMemoryError`.
- You can check for `Throwable`s by using `@Test(expected = OutOfMemoryError.class)`. 
- You're testing two cases in one method. It's best to split this into two methods. This makes pinpointing the problem easier when a failure occurs.
- The test methods should have a name that says what they want to test, e.g. `allocateArrayFailsForNegativeSizes` . It's fine if these names are long because the methods are called by the test harness (i.e. you don't have to write their names out because you want to call them) and because they don't belong to the "vocabulary" of the system (i.e. you don't have to remember the names). On the flip side, a descriptive name helps to show what the methods are supposed to test. That's very helpful when looking at tests a few months later.
- Externally visible output in unit tests should be avoided where possible. If you wanted to keep the message, you could just delete the `sysWriteln` invocations and use `fail(String)` which is provided by JUnit.
- The tests don't cover the modifications in `newTIB`. If it's not possible to write a test for this, you could just extract the size check into a new method and use an `@Inline` annotation on it to make sure that nothing changes for builds where the bootimage is built with the optimizing compiler.
- Adding a few simple positive tests would be beneficial.

**Comment by dmitry-brizhinev** [comment]
Updated.
Not sure if all the boilerplate to set up the parameters makes the tests better or worse.
I can change those back if you prefer the old style.

**Comment by erik-brangs** [comment]
The current style is fine by me. However, the current commit has an unneeded import of `org.jikesrvm.VM`. that fails the Checkstyle checks.

Apart from that, the patch looks almost ready. A few minor points:
- you could improve the commit message by mentioning which size checks are affected (e.g. "size checks for allocation of TIBs and arrays in MemoryManager")
- in `newTIBTestPositive`, you could also check that returned TIB is non-null, e.g. by using `assertNotNull`.

**Comment by dmitry-brizhinev** [comment]
Made the changes, and added two more test cases that occurred to me overnight

**Comment by erik-brangs** [comment]
Thanks.

**Pull request merged**
