### PR TITLE
Fixed several PPC bugs

### PR DESCRIPTION
**Pull request by dmitry-brizhinev**
Bug fixes as tested by erik

STATEMENT OF ORIGIN FOR A SINGLE CONTRIBUTOR

I, Dmitry Brizhinev: 

(a) represent that either:

  (i) I am the only author and owner of the contributed software 
      (described as/entitled "fixed several PPC bugs"), 
      which was neither derived nor copied from any other software,
  or 

 (ii) that any exception to (i) is software which was obtained under the 
      EPL (Eclipse Public License), 

and   

(b)  hereby agree to license this contributed software under the EPL.

### CODE REVIEW

**Comment by erik-brangs** [comment]
Thanks for your pull request.

Do you want to have all those commits merged or only the first one? I'm asking because the contributor statement only seems to cover the first commit. The first two commits look ok.

In the third commit, the check for the stack size makes the constructor of `RVMThread` hard to read. I would suggest that the check be moved to `MemoryManager.newStack`: If assertions are enabled, dump the invalid stack size and crash immediately. Otherwise, silently convert the invalid size to  `StackFrameLayout.getStackSizeNormal()` and continue.

**Comment by dmitry-brizhinev** [comment]
I had meant to only suggest the first one. Since the second one is okay, I can add the statement for it as well:

STATEMENT OF ORIGIN FOR A SINGLE CONTRIBUTOR

I, Dmitry Brizhinev:

(a) represent that either:

(i) I am the only author and owner of the contributed software 
(described as/entitled "Removed dead code"), 
which was neither derived nor copied from any other software,
or

(ii) that any exception to (i) is software which was obtained under the 
EPL (Eclipse Public License),

and

(b) hereby agree to license this contributed software under the EPL.

**Comment by erik-brangs** [comment]
Thanks for your contributions. I've merged the first two commits to the master branch.

**Comment by erik-brangs** [comment]
The stack size problems have been fixed in https://github.com/JikesRVM/JikesRVM/commit/6c00bd87d8d9393a32f9112ae4f2c1cd26cf6df0 so I'm closing this pull request.

**Pull request closed without merging**
