### PR TITLE
Overriding non-existing methods because of typo

### PR DESCRIPTION
**Pull request by caizixian**
cc @Pavlos1

### CODE REVIEW

**Comment by caizixian** [comment]
cc @Pavlos1

**Comment by erik-brangs** [comment]
Thanks.

Could you change the commit message to reflect what the commit does? I was thinking of something along the lines of "Fix typo that was causing a build failure in mmtk harness."

**Comment by caizixian** [comment]
@erik-brangs I've rephrased it.

**Comment by erik-brangs** [comment]
Thanks.

**Pull request merged**
